/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Alberth
 */
public class agenda extends javax.swing.JFrame {

    /**
     * Creates new form agenda
     */
    public agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        idText3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        idText = new javax.swing.JLabel();
        idText1 = new javax.swing.JLabel();
        idText2 = new javax.swing.JLabel();
        idText4 = new javax.swing.JLabel();
        idText5 = new javax.swing.JLabel();
        idText6 = new javax.swing.JLabel();
        agendaText = new javax.swing.JLabel();
        painelAgenda = new javax.swing.JLabel();
        fundoAgenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Luiz", "Corte", "35.00", "10/09/2024", "11:45", "N/A"},
                {"2", "Pedro ", "Corte + Barba", "50.00", "11/09/2024", "14:30", "N/A"},
                {"3", "Luiz Gustavo", "Sombrancelha", "15.00", "09/09/2024", "12:45", null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Horário", "Observação"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 1330, 270));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 260, 560, 300));

        jToggleButton1.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButton1.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Agendar Horário");
        jToggleButton1.setActionCommand("");
        jToggleButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 570, 560, 40));

        idText3.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        idText3.setForeground(new java.awt.Color(255, 255, 255));
        idText3.setText("Observação");
        getContentPane().add(idText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 150, 30));

        jTextField4.setText("0");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 330, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 330, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabelo", "Barba", "Sombrancelha", "Progressiva", "Relaxamento", "Descoloração", "Depilação Nasal e Auricular", "COMBO [EXECUTIVO]", " ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 330, 40));

        jTextField5.setText("0");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 330, 40));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 330, 40));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 330, 40));

        idText.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        idText.setForeground(new java.awt.Color(255, 255, 255));
        idText.setText("Data");
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 120, 20));

        idText1.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        idText1.setForeground(new java.awt.Color(255, 255, 255));
        idText1.setText("Cliente");
        getContentPane().add(idText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 100, 20));

        idText2.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        idText2.setForeground(new java.awt.Color(255, 255, 255));
        idText2.setText("ID");
        getContentPane().add(idText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, 20));

        idText4.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        idText4.setForeground(new java.awt.Color(255, 255, 255));
        idText4.setText("Serviço");
        getContentPane().add(idText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 100, 20));

        idText5.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        idText5.setForeground(new java.awt.Color(255, 255, 255));
        idText5.setText("Hora");
        getContentPane().add(idText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 70, 20));

        idText6.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        idText6.setForeground(new java.awt.Color(255, 255, 255));
        idText6.setText("Valor R$");
        getContentPane().add(idText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 120, 20));

        agendaText.setFont(new java.awt.Font("JetBrains Mono", 1, 50)); // NOI18N
        agendaText.setForeground(new java.awt.Color(255, 255, 255));
        agendaText.setText("Agenda");
        getContentPane().add(agendaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 190, 70));

        painelAgenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alberth\\Desktop\\fundooo.png")); // NOI18N
        getContentPane().add(painelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 1100));

        fundoAgenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alberth\\Downloads\\menu.jpg")); // NOI18N
        getContentPane().add(fundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agendaText;
    private javax.swing.JLabel fundoAgenda;
    private javax.swing.JLabel idText;
    private javax.swing.JLabel idText1;
    private javax.swing.JLabel idText2;
    private javax.swing.JLabel idText3;
    private javax.swing.JLabel idText4;
    private javax.swing.JLabel idText5;
    private javax.swing.JLabel idText6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel painelAgenda;
    // End of variables declaration//GEN-END:variables
}
