/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Alberth
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senhaCampo = new javax.swing.JPasswordField();
        usuarioCampo = new javax.swing.JTextField();
        senhaTexto = new javax.swing.JLabel();
        usuarioTexto = new javax.swing.JLabel();
        loginTexto = new javax.swing.JLabel();
        painelTransparente = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(senhaCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 380, 30));

        usuarioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCampoActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 380, 30));

        senhaTexto.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        senhaTexto.setForeground(new java.awt.Color(255, 255, 255));
        senhaTexto.setText("Senha");
        getContentPane().add(senhaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 80, 40));

        usuarioTexto.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        usuarioTexto.setForeground(new java.awt.Color(255, 255, 255));
        usuarioTexto.setText("Usuário");
        getContentPane().add(usuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 100, 50));

        loginTexto.setFont(new java.awt.Font("JetBrains Mono", 1, 48)); // NOI18N
        loginTexto.setForeground(new java.awt.Color(255, 255, 255));
        loginTexto.setText("LOGIN");
        getContentPane().add(loginTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 150, 50));

        painelTransparente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alberth\\Downloads\\login-painel (1).png")); // NOI18N
        painelTransparente.setText("jLabel2");
        painelTransparente.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(painelTransparente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 700, 570));

        fundo.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 12)); // NOI18N
        fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alberth\\Downloads\\login.jpeg")); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioCampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel loginTexto;
    private javax.swing.JLabel painelTransparente;
    private javax.swing.JPasswordField senhaCampo;
    private javax.swing.JLabel senhaTexto;
    private javax.swing.JTextField usuarioCampo;
    private javax.swing.JLabel usuarioTexto;
    // End of variables declaration//GEN-END:variables
}
